project_id = "jbrjsvkdnyzptkxnflbe"

[functions.availability]
verify_jwt = false

[functions.public-business]
verify_jwt = false

[functions.create-booking]
verify_jwt = false

[functions.create-preference]
verify_jwt = false

[functions.appointment]
verify_jwt = false

[functions.cancel-booking]
verify_jwt = false

[functions.mercadopago-webhook]
verify_jwt = false

[functions.create-business-admin]
verify_jwt = true
