project_id = "jbrjsvkdnyzptkxnflbe"

[functions.availability]
verify_jwt = false

[functions.public-business]
verify_jwt = false

[functions.create-booking]
verify_jwt = false

[functions.create-preference]
verify_jwt = false

[functions.update-business-services]
verify_jwt = false

[functions.appointment]
verify_jwt = false

[functions.cancel-booking]
verify_jwt = false

[functions.mercadopago-webhook]
verify_jwt = false

[functions.create-business-admin]
verify_jwt = true

[functions.soypobre-feed]
verify_jwt = true

[functions.soypobre-donation]
verify_jwt = true

[functions.soypobre-ranking]
verify_jwt = true

[functions.soypobre-donor-profile]
verify_jwt = true
